// Focused UI-only check. Uses an existing Playwright installation; no server or DB.
// PLAYWRIGHT_MODULE may name an absolute path to an installed @playwright/test.
const { chromium, expect } = require(process.env.PLAYWRIGHT_MODULE || '@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'apps/admin-web/index.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'apps/admin-web/src/main.js'), 'utf8');

(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const context = await browser.newContext({ locale: 'ja-JP' });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    let initialized = false, apiCalls = 0;
    await context.route('https://admin.test/**', async route => {
      const url = new URL(route.request().url()), p = url.pathname;
      if (p === '/') return route.fulfill({ contentType: 'text/html', body: html });
      if (p === '/admin.js') return route.fulfill({ contentType: 'text/javascript', body: js });
      apiCalls++;
      let data;
      if (p === '/admin/status') data = { initialized, ready: initialized, engine: initialized ? 'running' : 'not started', restart_required: true };
      else if (p === '/admin/initialize') { initialized = true; data = { temporary_password: 'temporary-fixture-secret', message: 'Initialized. Save the one-time password, start the engine, then sign in and change it.' }; }
      else if (p === '/admin/settings') data = { values: { 'server.bind': '127.0.0.1:8080', 'world.default_capacity': 32 }, manifest: { version: 1, bindings: [] }, read_only: false };
      else if (p.endsWith('/auth/login')) data = { access_token: 'fixture-only' };
      else if (p.endsWith('/auth/me')) data = { display_name: 'Users', login_id: 'operator' };
      else if (p.endsWith('/users/u1/roles')) data = { role_ids: ['r1'] };
      else if (p.endsWith('/users')) data = { items: [{ id: 'u1', login_id: 'operator', display_name: 'Users', enabled: true }], next_cursor: 'next-fixture' };
      else if (p.endsWith('/roles')) data = { items: [{ id: 'r1', name: 'Roles', description: 'Description', permissions: ['admin.roles.assign'] }], next_cursor: null };
      else if (p.endsWith('/worlds')) data = { items: [{ id: 'w1', name: 'World', status: 'active' }], next_cursor: null };
      else if (p.endsWith('/instances')) data = { items: [{ id: 'i1', world_id: 'w1', status: 'running' }], next_cursor: null };
      else if (p === '/admin/check') return route.fulfill({ status: 400, json: { message: 'database.url: RAW diagnostic 日本語 / 42' } });
      else throw new Error(`Unexpected fixture request ${p}`);
      return route.fulfill({ json: data });
    });
    await page.goto('https://admin.test/#fixture-capability');
    await expect(page.locator('html')).toHaveAttribute('lang', 'ja');
    await expect(page.locator('#setup')).toBeVisible();
    await expect(page.locator('h1')).toHaveText('エンジン管理');
    await page.locator('#setupForm button[type=submit]').click();
    assert.equal(await page.locator('#databaseUrl').evaluate(el => el.validationMessage), '値を入力してください。');
    await page.locator('#language').selectOption('en');
    assert.equal(await page.locator('#databaseUrl').evaluate(el => el.validationMessage), 'Enter a value.');
    await page.locator('#databaseUrl').fill('postgresql://fixture/password');
    await page.locator('#adminLogin').fill('operator');
    await page.locator('#adminName').fill('Users');
    await page.locator('input[value=development]').check();
    await page.locator('#language').selectOption('ja');
    await expect(page.locator('#databaseUrl')).toHaveValue('postgresql://fixture/password');
    await expect(page.locator('input[value=development]')).toBeChecked();
    await expect(page.locator('#devWarning')).toBeVisible();
    await page.locator('#checkConnection').click();
    await expect(page.locator('#message')).toHaveText('サーバーからの応答: database.url: RAW diagnostic 日本語 / 42');
    await page.locator('#language').selectOption('en');
    await expect(page.locator('#message')).toHaveText('Server response: database.url: RAW diagnostic 日本語 / 42');
    await page.locator('#setupForm button[type=submit]').click();
    await expect(page.locator('#login')).toBeVisible();
    await page.locator('#loginPassword').fill('temporary-fixture-secret');
    await page.locator('#language').selectOption('ja');
    await expect(page.locator('#loginPassword')).toHaveValue('temporary-fixture-secret');
    await expect(page.locator('#credentialValue')).toHaveText('temporary-fixture-secret');
    await page.locator('#loginForm button').click();
    await expect(page.locator('#usersTable')).toContainText('有効');
    await expect(page.locator('#signedIn')).toHaveText('ログイン中: Users (operator)');
    await page.locator('#newLogin').fill('unsaved-user');
    await page.locator('#currentPassword').fill('old-fixture-password');
    await page.locator('#newPassword').fill('short');
    await page.locator('#passwordForm button').click();
    assert.equal(await page.locator('#newPassword').evaluate(el => el.validationMessage), '12 文字以上で入力してください。');
    await page.locator('#users details summary').click();
    await expect(page.locator('#roleChoices input')).toBeChecked();
    await page.locator('#roleChoices input').uncheck();
    const before = apiCalls;
    await page.locator('#language').selectOption('en');
    assert.equal(apiCalls, before, 'Language switch must not reload data');
    await expect(page.locator('#roleChoices input')).not.toBeChecked();
    await expect(page.locator('#users details')).toHaveAttribute('open', '');
    await expect(page.locator('#newLogin')).toHaveValue('unsaved-user');
    await expect(page.locator('#newPassword')).toHaveValue('short');
    assert.equal(await page.locator('#newPassword').evaluate(el => el.validationMessage), 'Use at least 12 characters.');
    await expect(page.locator('#usersTable')).toContainText('Users');
    await expect(page.locator('#moreUsers')).toBeVisible();
    await page.locator('[data-tab=roles]').click();
    await expect(page.locator('#rolesTable')).toContainText('admin.roles.assign');
    await page.locator('#roleName').fill('unsaved-role');
    await page.locator('#language').selectOption('ja');
    await expect(page.locator('#roleName')).toHaveValue('unsaved-role');
    await expect(page.locator('#rolesTable td').nth(0)).toHaveText('Roles');
    await expect(page.locator('#rolesTable td').nth(1)).toHaveText('Description');
    await page.locator('[data-tab=worlds]').click();
    await expect(page.locator('#instancesTable')).toContainText('稼働中');
    await page.locator('#worldName').fill('unsaved-world');
    await page.locator('#worldCapacity').fill('0');
    await page.locator('#worldForm button').click();
    assert.equal(await page.locator('#worldCapacity').evaluate(el => el.validationMessage), '1 以上の値を入力してください。');
    await page.locator('#language').selectOption('en');
    await expect(page.locator('#worldName')).toHaveValue('unsaved-world');
    await expect(page.locator('#instancesTable')).toContainText('running');
    await page.locator('[data-tab=config]').click();
    await expect(page.locator('#configFields input')).toHaveCount(2);
    await page.locator('#configFields input').first().fill('127.0.0.1:8888');
    await page.locator('#replacementDb').fill('replacement-fixture');
    await page.locator('#manifest').fill('{ invalid raw json');
    await page.locator('#saveSettings').click();
    await expect(page.locator('#message')).toContainText('Invalid JSON manifest.');
    await page.locator('#language').selectOption('ja');
    await expect(page.locator('#message')).toContainText('JSON マニフェストが不正です。');
    await expect(page.locator('#manifest')).toHaveValue('{ invalid raw json');
    await expect(page.locator('#replacementDb')).toHaveValue('replacement-fixture');
    await expect(page.locator('#configFields input').first()).toHaveValue('127.0.0.1:8888');
    await expect(page.locator('[data-tab=config]')).toHaveAttribute('aria-selected', 'true');
    await page.locator('#language').selectOption('en');
    await page.reload();
    await expect(page.locator('html')).toHaveAttribute('lang', 'en');
    assert.deepEqual(errors, []);
    await context.close();
    for (const locale of ['en-US', 'fr-FR']) {
      const fresh = await browser.newContext({ locale });
      await fresh.route('https://admin.test/**', route => route.fulfill({ contentType: route.request().url().endsWith('admin.js') ? 'text/javascript' : 'text/html', body: route.request().url().endsWith('admin.js') ? js : html }));
      const tab = await fresh.newPage();
      await tab.goto('https://admin.test/');
      await expect(tab.locator('html')).toHaveAttribute('lang', 'en');
      await expect(tab.locator('#language')).toBeVisible();
      await fresh.close();
    }
    console.log('PASS: Japanese/English defaults, persistence, real controls, setup/login/password validation, all management sections, retained form/state/credentials, raw diagnostics, no switch API calls.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
